name: gavinmart
favicon: null
layout_spectrum: 0.23678120481781662
typography_spectrum: 0.8329515964724123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eee6d7'
    - '#bfb09c'
    - '#342a23'
    - '#5f5952'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
